
[package]
name        = "desktop-wf"
version     = "0.1.0"
authors     = ["Namilskyy <alive6863@gmail.com>"]
edition     = "20"
license     = "CC-BY-NC-SA 4.0"
description = "Desktop mate analogue for GNU/Linux" 

c_flags = ["-Iinclude", "-I/usr/include/SDL2", "-I/usr/include/assimp"]
cxx_flags = ["-std=c++14", "-Iinclude", "-I/usr/include/SDL2", "-I/usr/include/assimp"]
ld_flags = ["-L/usr/lib", "-lSDL2", "-lGL", "-lX11", "-lwayland-client", "-lassimp", "-lgio-2.0"]
c_std = "ansi"
cpp_std = "c++20"

# Libraries (array tables)
[[lib]]
name = "CoordSys"
type = "shared"
sources = ["src/CoordSys.c"]
includes = ["include"]
links = ["GL"]

[[lib]]
name = "WaylandWindow"
type = "shared"
sources = ["src/WaylandWindow.c"]
includes = ["include", "/usr/include/wayland"]
links = ["wayland-client"]

[[lib]]
name = "XelevenWindow"
type = "shared"
sources = ["src/XelevenWindow.c"]
includes = ["include", "/usr/include/X11"]
links = ["X11"]

# Objects (array tables)
[[object]]
name = "D-IPC-TK"
sources = ["src/D-IPC-TK.c"]
includes = ["include"]
links = ["SDL2"]

[[object]]
name = "Display"
sources = ["src/Display.cpp"]
includes = ["include", "/usr/include/SDL2"]
links = ["SDL2", "GL"]

[[object]]
name = "main"
sources = ["src/main.cpp"]
includes = ["include", "/usr/include/SDL2", "/usr/include/assimp"]
links = ["SDL2", "GL", "assimp"]

[[object]]
name = "test"
sources = ["src/test.cpp"]
includes = ["include", "/usr/include/SDL2"]
links = ["SDL2"]

[link]
output = "final_binary"
objects = ["D-IPC-TK.o", "Display.o", "main.o", "target/release/Ediotor.o", "target/release/Handler.o", "target/release/gui.o"]
