[package]
name         = "Dekstop-WF"
version      = "0.0.1"
description  = "Desktop mate analogue for GNU/Linux"
license      = "CC-BY-NC-SA 4.0"
edition      = "2021"

[build]
rustflags = ["-emit=obj"]

[[bin]]
name = "editor"
path = "src/Editor.rs"

[[bin]]
name = "gui"
path = "src/GUI.rs"
